name: Terraform validation with terratest

on:
  workflow_dispatch:
  pull_request:

jobs:
  teratest:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache: false

      - name: Install dependencies
        run: go get .
        working-directory: "${{ github.workspace }}/tests"

      - name: Test
        run: go test -v
        working-directory: "${{ github.workspace }}/tests"
